[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"

[[redirects]]
    from = "/about-me/"
    to = "/about"
    status = 301

[[redirects]]
    from = "/projects/"
    to = "/portfolio"
    status = 301

[[redirects]]
    from = "/contact/"
    to = "/contact"
    status = 301

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200